### PR TITLE
feat: Incremental Static Build

### PR DESCRIPTION
**Pull request by tlgimenes**
## What's the purpose of this pull request?
This PR uses the new WebOps capability called Incremental Static Builds. This should drastically improve response times and reduce infrastructure usage on deferred pages, like PDPs and PLPs

## How does it work?
WebOps recently released this Incremental Static Build feature. To use on Next.JS, make sure to use `getStaticProps` and `getStaticPaths` APIS and enable `USE_STALE_CACHE=true` on `vtex.env`.

## How to test it?
Open a PDP. Check the response header called `x-faststore-cache`. The first request should give you a `MISS`. The second request should give you `HIT`. Note that `HIT`s are much faster than `MISS`. Also, note that all subsequent requests have a HIT as value. 

## References
- Original PR on WebOps: https://github.com/vtex/vtex-cicd-platform/pull/105

### CODE REVIEW

**Review by eduardoformiga — APPROVED** [review]

**Review by eduardoformiga — COMMENTED** [review]
I tried to test it on the preview link, but I got `x-faststore-cache: BYPASS` for all the graphql requests. 
Am I testing it right?

**Comment by tlgimenes** [comment]
> > > I tried to test it on the preview link, but I got `x-faststore-cache: BYPASS` for all the graphql requests. Am I testing it right?
> > 
> > 
> > Oh, you may be using a hard refresh. If you press `cmd+shift+r` chrome will add a `Pragma: no-cache` header that will bypass all cache layers. Try openning a new anonymous window instead of `cmd+shift+r`.
> 
> I got `no-cache` for a soft refresh as well (anonymous tab). As we can see in the image below: CqJTHyOt00

Oh, because you have disabled the cache on your browser. Try unchecking this button:
image

**Comment by eduardoformiga** [comment]
> 

That's true, @tlgimenes. My bad! Now I unchecked it and test again and got `x-faststore-cache: MISS` on every refresh. Don't know what is happening  🤔

**Review by eduardoformiga — APPROVED** [review]
YAY, It works! 🎉

**Pull request merged**
