### PR TITLE
fix: update builder files to the new implementation

### PR DESCRIPTION
**Pull request by myllenaalves**
## What's the purpose of this pull request?

<em>Change to the new implementation of the builder files.</em>

## How does it work?

Add builder argument to the cms sync command.
Related to this pr: https://github.com/vtex/cli-plugin-cms/pull/16.

## How to test it?

<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>

## References

<em>Spread the knowledge: is any content you used to create this PR worth sharing?</em>

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

## Checklist

<em>You may erase this after checking them all :wink:</em>

**PR Title and Commit Messages**
- [X] PR title and commit messages follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification
  - Available prefixes: `feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, and `test`

**PR Description**
- [ ] Added a label according to the PR goal - `Breaking change`, `Features`, `Bug fixes`, `Chore`, `Documentation`, `Style changes`, `Refactoring`, `Performance`, and `Test`
- [ ] Added the component, hook, or path name in-between backticks (\`\`) - *if applicable, e.g., `ComponentName` component, `useWindowDimensions` hook*

**Dependencies**
- [ ] Committed the `yarn.lock` and `bun.lockb` file when there were changes to the packages

**Documentation**
- [ ] PR description
- [ ] Added to/Updated the Storybook - *if applicable*
- [ ] For documentation changes, ping `@carolinamenezes` or `@PedroAntunesCosta` to review and update

### CODE REVIEW

**Review by mateuspontes — APPROVED** [review]

**Comment by mateuspontes** [comment]
This PR should be merged after we update the CLI to sync data on CMS.

**Comment by eduardoformiga** [comment]
looks redundant to me as well.

🎗️  If we decide on merging this. We also need to update the Faststore cli [CMS folder](https://github.com/vtex/faststore/blob/main/packages/cli/src/utils/directory.ts#L27).

**Comment by mateuspontes** [comment]
That's the name we use to identify the build inside the CMS, the user can have multiple builders, eg. `faststore`, `newsletter`, `qa`, and many more. So we're identifying the default files as `faststore`, and yes, the documentation must be updated, so we're updating first here.

**Comment by emersonlaurentino** [comment]
@mateuspontes the files are different between builders? because if not, there could be a cms config file that the store informs the builder.

**Comment by mateuspontes** [comment]
@emersonlaurentino yes, they may be different. The user may want to store different files from the store on prod, qa, and mobile, inside the same repository, so we're separating them inside their folders, not necessarily this repository, but it's the new convention.

**Comment by myllenaalves** [comment]
Do you have something that wasn't answered about  it? Because the changes is already in prod in the **CMS cli** and we have to update here too. We already update this documentation: https://www.faststore.dev/tutorials/cms/2 and we are working in improve with a section only to explain the **CMS cli**. @emersonlaurentino @eduardoformiga.

**Review by emersonlaurentino — APPROVED** [review]

**Review by eduardoformiga — APPROVED** [review]
LGTM!

**Pull request merged**
